### PR TITLE
Add package-lock.json to .gitignore

### PR DESCRIPTION
**Pull request by jinmel**

### CODE REVIEW

**Comment by draffensperger** [comment]
Could you explain the motivation for this?

My understanding was that package locks should be committed to ensure reproducible builds. See also this [StackOverflow question](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) about it.

**Comment by jinmel** [comment]
@draffensperger then we should commit the result after npm install on root package shouldn't we?

**Comment by mayurkale22** [comment]
> Could you explain the motivation for this?
> 
> My understanding was that package locks should be committed to ensure reproducible builds. See also this [StackOverflow question](https://stackoverflow.com/questions/44206782/do-i-commit-the-package-lock-json-file-created-by-npm-5) about it.

+1. I think package-lock is required to ensure a consistent install and compatible dependencies, especially on shared projects like this one.

**Comment by jinmel** [comment]
@mayurkale22 is your opinion on saving package-lock.json to repo?

**Comment by mayurkale22** [comment]
> @mayurkale22 is your opinion on saving package-lock.json to repo?

I have already added my opinion here https://github.com/census-instrumentation/opencensus-node/pull/422#issuecomment-472560143. I think we should continue to commit package-lock to repo.

**Comment by jinmel** [comment]
understood. closing this PR

**Pull request closed without merging**
