### PR TITLE
Use Travis CI

### LINKED ISSUE #507: Migrate to TravisCI
OpenTelemetry is also going to use TravisCI. 

Proposal (Infrastructure requirements): https://github.com/cncf/toc/blob/master/proposals/opentelemetry.adoc

### PR DESCRIPTION
**Pull request by mayurkale22**
Fixes #507

### CODE REVIEW

**Comment by mayurkale22** [comment]
> I'm curious, what's the motivation for using Travis when we already have CircleCI for this repo?

OpenTelemetry is also going to use TravisCI, to make things consistent I thought to use TravisCI here. Sounds good?

**Comment by draffensperger** [comment]
Makes sense, thanks for explaining!

**Comment by mayurkale22** [comment]
> Makes sense, thanks for explaining!

I will get rid of CircleCI, TravisCI looks stable.

**Comment by aabmass** [comment]
Closing since Travis CI is not recommended for Google projects anymore. Also, OTel is using Github Actions most places now

**Pull request closed without merging**
