### PR TITLE
Renames [registeredViews] to [measurmentMap]

### PR DESCRIPTION
**Pull request by isaikevych**

### CODE REVIEW

**Comment by mayurkale22** [comment]
@isaikevych I am little confused, why are we renaming the map? registeredViews make more sense to store view with a corresponding measure name. Let me know if I am missing something here.

**Comment by isaikevych** [comment]
> @isaikevych I am little confused, why are we renaming the map? registeredViews make more sense to store view with a corresponding measure name. Let me know if I am missing something here.

@mayurkale22 and @songy23 we discussed this changes one week ago

**Comment by mayurkale22** [comment]
> > @isaikevych I am little confused, why are we renaming the map? registeredViews make more sense to store view with a corresponding measure name. Let me know if I am missing something here.
> 
> @mayurkale22 and @songy23 we discussed this changes one week ago

We discussed to add measurmentMap for stats recorder, similar to other libraries. example: 
```
// python
measure_map = stats_recorder.new_measurement_map()
measure_map.measure_int_put(VIDEO_SIZE_MEASURE, 25 * MiB)
measure_map.record(tag_map)
```
With this user can record all the measures at the same time with a tags. @songy23 correct me if I miss anything here.

**Comment by isaikevych** [comment]
> > > @isaikevych I am little confused, why are we renaming the map? registeredViews make more sense to store view with a corresponding measure name. Let me know if I am missing something here.
> > 
> > 
> > @mayurkale22 and @songy23 we discussed this changes one week ago
> 
> We discussed to add measurmentMap for stats recorder, similar to other libraries. example:
> 
> ```
> // python
> measure_map = stats_recorder.new_measurement_map()
> measure_map.measure_int_put(VIDEO_SIZE_MEASURE, 25 * MiB)
> measure_map.record(tag_map)
> ```
> With this user can record all the measures at the same time with a tags. @songy23 correct me if I miss anything here.

@mayurkale22 We didnt discuss `adding measurmentMap for stats recorder,` - we discussed rename it

**Pull request closed without merging**
