### PR TITLE
Fix up typos in source

### PR DESCRIPTION
**Pull request by xginn8**

### CODE REVIEW

**Comment by bogdandrutu** [comment]
Please fix the build

**Comment by justindsmith** [comment]
@xginn8 Looks like all you need to do is run `npm run fix` in the `opencensus-exporter-prometheus` package to fix the build.

Are you able to get this PR ready for submission? Looks straight-forward, so we can merge it quickly.

**Comment by xginn8** [comment]
@justindsmith thanks for taking a look, I had forgotten about this PR. PTAL!

**Comment by justindsmith** [comment]
@isaikevych Can you take a quick look. I think we can safely merge this now.

**Comment by songy23** [comment]
@justindsmith Added you to the collaborator list of this repo, you should be able to merge PRs now.

**Pull request merged**
