### PR TITLE
fix: core version

### LINKED ISSUE #752: Module not found: Error: Can't resolve '../../package.json' in /node_modules/@opencensus/core/build/src/common'
Please answer these questions before submitting a bug report.

### What version of OpenCensus are you using?
```0.0.19```

### What version of Node are you using?
```12.4.0```

### What did you do?
If possible, provide a recipe for reproducing the error.
I am running the angular universal build for production and I got the error below:
```
ERROR in ./node_modules/@opencensus/core/build/src/common/version.js
Module not found: Error: Can't resolve '../../package.json' in '{PATH}/universal/node_modules/@opencensus/core/build/src/common'
 @ ./node_modules/@opencensus/core/build/src/common/version.js 28:12-41
 @ ./node_modules/@opencensus/core/build/src/index.js
 @ ./node_modules/@opencensus/exporter-zipkin/build/src/zipkin.js
 @ ./node_modules/@opencensus/exporter-zipkin/build/src/index.js
 @ ./server.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-io-example@1.0.0 webpack:server: `webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 2
```
### What did you expect to see?
```No such error as above```

### What did you see instead?
```
ERROR in ./node_modules/@opencensus/core/build/src/common/version.js
Module not found: Error: Can't resolve '../../package.json' in '{PATH}/universal/node_modules/@opencensus/core/build/src/common'
 @ ./node_modules/@opencensus/core/build/src/common/version.js 28:12-41
 @ ./node_modules/@opencensus/core/build/src/index.js
 @ ./node_modules/@opencensus/exporter-zipkin/build/src/zipkin.js
 @ ./node_modules/@opencensus/exporter-zipkin/build/src/index.js
 @ ./server.ts
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! angular-io-example@1.0.0 webpack:server: `webpack --config webpack.server.config.js --progress --colors`
npm ERR! Exit status 2
```
### Additional context

```
I am using **opencensus** for tracing outbound calls in nodejs with **zipkin** dashboard.
Here are packages added in **package.json** under **dependencies**.
```

```
"@opencensus/exporter-zipkin": "0.0.19",
"@opencensus/nodejs": "0.0.19",
"@opencensus/propagation-b3": "0.0.19",
```
Here is the implementation in `server.ts` file:
```
...
// start opencensus
const oTracing = require('@opencensus/nodejs');
const oPropagation = require('@opencensus/propagation-b3');
const proB3 = new oPropagation.B3Format();
const { ZipkinTraceExporter } = require('@opencensus/exporter-zipkin');
// setup zipkin tracing
function generateExpressTracing() {
  try {
    // Add your zipkin url (ex http://localhost:9411/api/v2/spans)
    // and application name to the Zipkin options
    const configZipkin = {
      "zipkinUrl": "http://localhost:9411/api/v2/spans",
      "appName": "digital-p2p",
      "traceOptions": {
        "samplingRate": 1,
        "bufferSize": 1,
        "bufferTimeout": 1,
        "logLevel": 1
      }
    };
    const zipkinOptions = {
      url: configZipkin.zipkinUrl,
      serviceName: configZipkin.appName
    };
    const zExporter = new ZipkinTraceExporter(zipkinOptions);
    // start tracing
    oTracing.start({
      zExporter,
      propagation: proB3,
      samplingRate: configZipkin.traceOptions.samplingRate,
      bufferSize: configZipkin.traceOptions.bufferSize,
      bufferTimeout: configZipkin.traceOptions.bufferTimeout,
      logLevel: configZipkin.traceOptions.logLevel // `1` show errors, if any
    });
  } catch (_err) {
    console.log('Error cause by opencensus tracing express.');
  }
}
generateExpressTracing();
// end setup opencensus exporter report
...
```

### PR DESCRIPTION
**Pull request by mayurkale22**
Resolves #752

### CODE REVIEW

**Comment by mayurkale22** [comment]
@tclyit @draffensperger Please review

**Comment by mayurkale22** [comment]
@tclyit @draffensperger Thank you :)

**Comment by tclyit** [comment]
> @tclyit @draffensperger Thank you :)

I am wondering when this fix is published to npm release package?
Thank you so much @mayurkale22 and @draffensperger for this support.

**Comment by mayurkale22** [comment]
> I am wondering when this fix is published to npm release package?
> Thank you so much @mayurkale22 and @draffensperger for this support.

I will cut the release early next week (most probably Tuesday, 18th). I hope that's ok with you.

**Comment by tclyit** [comment]
Thank you so much.

**Pull request merged**
