### PR TITLE
fix(resources): GKE pod name label

### LINKED ISSUE #727: exporter/stackdriver: GKE pod name label incorrect
### What version of OpenCensus are you using?

0.0.19

### What version of Node are you using?

12.14.1

### What did you do?

record metrics in a GKE container

### What did you expect to see?

The pod name label should be correct.

### What did you see instead?

The pod name label is wrong. It is the hostname from the metadata server which is not related to the pod (at least in my tests). The container hostname could be used instead.

### Additional context

I tried to fix this with https://github.com/census-instrumentation/opencensus-node/pull/726 but gave up after the CLA requirement.

### PR DESCRIPTION
**Pull request by mayurkale22**
Resolves #727

These changes have all been tested locally against a real GKE and Stackdriver instance and been confirmed to be working.

### CODE REVIEW

**Comment by fiws** [comment]
@mayurkale22 Thanks for addressing my issue. This looks like it solves my problem.

But: I did a bit of digging and found out that you can overwrite the hostname in the [pod spec](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#podspec-v1-core). So maybe this should be an environment variable with a fallback to the hostname?

**Comment by miguelgarcia** [comment]
Hello, I'm running into this issue and @mayurkale22 's code does indeed fix the problem. Any hint about when it will be merged ? Thanks a lot!

**Comment by mayurkale22** [comment]
@draffensperger Please review when you get a chance.

**Comment by mayurkale22** [comment]
> Hello, I'm running into this issue and @mayurkale22 's code does indeed fix the problem. Any hint about when it will be merged ? Thanks a lot!

Sorry for the delay, waiting for PR to get approved. I will include this in `0.0.20` release (#754).

**Comment by mayurkale22** [comment]
> Hello, I'm running into this issue and @mayurkale22 's code does indeed fix the problem. Any hint about when it will be merged ? Thanks a lot!

Published in `0.0.20`, let us know if you encounter any issues!

**Comment by miguelgarcia** [comment]
Working as expected by now, thanks !

**Comment by mayurkale22** [comment]
> Working as expected by now, thanks !

Ok great, thanks for the confirmation.

**Pull request merged**
