### PR TITLE
set CurrentRootSpan correctly

### PR DESCRIPTION
**Pull request by mayurkale22**
While debugging #526, I found we are not assigning `currentRootSpan` correctly, especially in case of tracer with cls. Ideally, we should set `currentRootSpan` before the `onStartSpan` event. This change is done in https://github.com/census-instrumentation/opencensus-node/commit/92edaa9d406ac74e1805a4e80b756acedc413001#diff-b46c2c01fbf239aae015e19185803e0dL154

The `onStartSpan` and `onEndSpan` events contains following check -> 
```
if (this.currentRootSpan.traceId !== root.traceId) {
      this.logger.debug(
          'currentRootSpan != root on notifyStart. Need more investigation.');
    }
```

### CODE REVIEW

**Comment by mayurkale22** [comment]
@hekike This is related to #484, Could you please review?

**Comment by hekike** [comment]
LGTM

Related topic: should a child span become a parent for the next child span with CLS? 
It's not really possible with the current sync `startChildSpan` interface as we need to update span in CLS context.

**Comment by mayurkale22** [comment]
> Related topic: should a child span become a parent for the next child span with CLS? It's not really possible with the current sync `startChildSpan` interface as we need to update span in CLS context.

Yes, currently it's not possible with `startChildSpan` interface. We already have issue for same https://github.com/census-instrumentation/opencensus-node/issues/256. If you are feeling motivated, maybe you can attempt to write solution and open a PR. :)

**Comment by hekike** [comment]
@mayurkale22 what do you think about this proposal https://github.com/census-instrumentation/opencensus-node/pull/498 it would make it possible.

**Pull request merged**
