### PR TITLE
Fix for non-null parentSpanId

### PR DESCRIPTION
**Pull request by tcolgate**

### CODE REVIEW

**Comment by tcolgate** [comment]
At this point the failing tests seem to be in the stackdriver exporter (unrelated to this change)

**Comment by fabiogomessilva** [comment]
Hi @tcolgate,

Thanks for your contribution.

Actually, it is just a tslint issue. 

```
lerna ERR! test Errored while running script in '@opencensus/exporter-jaeger'
...
lerna ERR! clang-format reported errors... run `gts fix` to address.
```
Please run 'gts fix' at package/opencensus-exporter-jaeger, run the tests again and commit the changes.

**Comment by tcolgate** [comment]
I might admit, I couldn't get the tests to run locally. They seem to fail, and I didn't see anything about gts in the output.

**Comment by fabiogomessilva** [comment]
Your last commit fixed the issue. I suppose you had managed to run the tests, right?

**Comment by tcolgate** [comment]
@fabiogomessilva no, but the gts fixed looked fine, I committed the result of that and let the CI tests run.
I'll try and get the tests working locally, but that may take me a while (node isn't my primary dev environment).

**Comment by tcolgate** [comment]
Is there a readme for setting up the dev environment?

**Comment by tcolgate** [comment]
@kjin I've added a test to check spans encode to the thrift spans. Seemed worth while, and forced me to get the local tests working.

**Comment by kjin** [comment]
@tcolgate I just rebased since the Node 6 CI doesn't seem to want to work otherwise (still the same issue as I mentioned earlier, though it appears not to be affecting other PRs for some reason). If this passes I will land it.

**Pull request merged**
