### PR TITLE
gRPC Trace: correct span name format

### PR DESCRIPTION
**Pull request by mayurkale22**
This change is as per specs: https://github.com/census-instrumentation/opencensus-specs/blob/master/trace/gRPC.md#spans

### CODE REVIEW

**Comment by draffensperger** [comment]
Should this logic go in the Stackdriver exporter instead of the gRPC instrumentation itself?

This is how I read the specs:

- *Name the spans by package, service, method and set span kind*: "Span name is formatted as (also known as full gRPC method name): $package.$service/$method", and "Outgoing requests should be a span kind of CLIENT and incoming requests should be a span kind of SERVER."
- *For backends (like Stackdriver Trace v2) that lack span kind, use a "Sent." or "Recv." prefix to incidate it*:  "For backends that does not support Span.Kind, the exported span names can be prefixed with Sent. (for CLIENT kind) and Recv. (for SERVER kind)."

**Comment by mayurkale22** [comment]
@draffensperger AFAIK, we append these prefixes (```Sent.``` and ```Recv.```) when gRPC call starts, for the client and server span name(s). Counterpart in [Java](https://github.com/grpc/grpc-java/blob/9a38dea91c6194f7a882e2be1c2846567e9cdcda/core/src/main/java/io/grpc/internal/CensusTracingModule.java#L415) and [Python](https://github.com/census-instrumentation/opencensus-python/blob/master/opencensus/trace/ext/grpc/client_interceptor.py#L252).

@songy23 correct me if I am wrong.

**Comment by draffensperger** [comment]
Interesting. The go library does it in the exporter, see https://github.com/census-ecosystem/opencensus-go-exporter-stackdriver/blob/d1e19f5c23e955d7b65ff59e935007a2edce045e/trace_proto.go#L55

Based on the specs, I think the Go library is doing it correctly and the Java/Python ones should be changed eventually.

@bogdandrutu - should span names be set with `Sent.` and `Recv.` when the span is created or when it is exported to Stackdriver?

**Comment by mayurkale22** [comment]
obsolete, closing this.

**Pull request closed without merging**
