### PR TITLE
Fix stackdriver test

### PR DESCRIPTION
**Pull request by mayurkale22**

### CODE REVIEW

**Comment by draffensperger** [comment]
Do we know why this broke?

**Comment by mayurkale22** [comment]
Looks like some internal auth library changed/updated, didn't spend long time in investigation. I hope that's ok. :)

**Comment by draffensperger** [comment]
Ah, I see. Maybe as a follow-up, should that test be checking for a 403 response code rather than a string in the response?

**Comment by mayurkale22** [comment]
> Ah, I see. Maybe as a follow-up, should that test be checking for a 403 response code rather than a string in the response?

Added check for response code. It's actually 401 (Unauthorized). :)

**Pull request merged**
